name: ESP32-S3 Build

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: espressif/idf:v5.2.1
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          . /opt/esp/idf/export.sh
          idf.py set-target esp32s3
          idf.py build
